# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_config.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(420, 270)
        self.gridLayoutWidget = QtWidgets.QWidget(Config)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 0, 5, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_config_io = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_config_io.setFont(font)
        self.comboBox_config_io.setObjectName("comboBox_config_io")
        self.comboBox_config_io.addItem("")
        self.comboBox_config_io.addItem("")
        self.gridLayout.addWidget(self.comboBox_config_io, 4, 5, 1, 1)
        self.comboBox_config_mode = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_config_mode.setFont(font)
        self.comboBox_config_mode.setObjectName("comboBox_config_mode")
        self.comboBox_config_mode.addItem("")
        self.comboBox_config_mode.addItem("")
        self.gridLayout.addWidget(self.comboBox_config_mode, 3, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.comboBox_config_parity = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_config_parity.setFont(font)
        self.comboBox_config_parity.setObjectName("comboBox_config_parity")
        self.comboBox_config_parity.addItem("")
        self.comboBox_config_parity.addItem("")
        self.comboBox_config_parity.addItem("")
        self.gridLayout.addWidget(self.comboBox_config_parity, 0, 5, 1, 1)
        self.comboBox_config_baud = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_config_baud.setFont(font)
        self.comboBox_config_baud.setObjectName("comboBox_config_baud")
        self.comboBox_config_baud.addItem("")
        self.comboBox_config_baud.addItem("")
        self.comboBox_config_baud.addItem("")
        self.comboBox_config_baud.addItem("")
        self.comboBox_config_baud.addItem("")
        self.comboBox_config_baud.addItem("")
        self.comboBox_config_baud.addItem("")
        self.comboBox_config_baud.addItem("")
        self.gridLayout.addWidget(self.comboBox_config_baud, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.comboBox_config_speedinair = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_config_speedinair.setFont(font)
        self.comboBox_config_speedinair.setObjectName("comboBox_config_speedinair")
        self.comboBox_config_speedinair.addItem("")
        self.comboBox_config_speedinair.addItem("")
        self.comboBox_config_speedinair.addItem("")
        self.comboBox_config_speedinair.addItem("")
        self.comboBox_config_speedinair.addItem("")
        self.comboBox_config_speedinair.addItem("")
        self.gridLayout.addWidget(self.comboBox_config_speedinair, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 3, 1, 1)
        self.comboBox_config_errcheck = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_config_errcheck.setFont(font)
        self.comboBox_config_errcheck.setObjectName("comboBox_config_errcheck")
        self.comboBox_config_errcheck.addItem("")
        self.comboBox_config_errcheck.addItem("")
        self.gridLayout.addWidget(self.comboBox_config_errcheck, 3, 2, 1, 1)
        self.comboBox_config_wakeuptime = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_config_wakeuptime.setFont(font)
        self.comboBox_config_wakeuptime.setObjectName("comboBox_config_wakeuptime")
        self.comboBox_config_wakeuptime.addItem("")
        self.comboBox_config_wakeuptime.addItem("")
        self.comboBox_config_wakeuptime.addItem("")
        self.comboBox_config_wakeuptime.addItem("")
        self.comboBox_config_wakeuptime.addItem("")
        self.comboBox_config_wakeuptime.addItem("")
        self.comboBox_config_wakeuptime.addItem("")
        self.comboBox_config_wakeuptime.addItem("")
        self.gridLayout.addWidget(self.comboBox_config_wakeuptime, 4, 2, 1, 1)
        self.lineEdit_config_loraaddress = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_config_loraaddress.setFont(font)
        self.lineEdit_config_loraaddress.setObjectName("lineEdit_config_loraaddress")
        self.gridLayout.addWidget(self.lineEdit_config_loraaddress, 5, 2, 1, 1)
        self.comboBox_config_senddb = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_config_senddb.setFont(font)
        self.comboBox_config_senddb.setObjectName("comboBox_config_senddb")
        self.comboBox_config_senddb.addItem("")
        self.comboBox_config_senddb.addItem("")
        self.comboBox_config_senddb.addItem("")
        self.comboBox_config_senddb.addItem("")
        self.gridLayout.addWidget(self.comboBox_config_senddb, 1, 5, 1, 1)
        self.lineEdit_config_channel = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_config_channel.setFont(font)
        self.lineEdit_config_channel.setObjectName("lineEdit_config_channel")
        self.gridLayout.addWidget(self.lineEdit_config_channel, 5, 5, 1, 1)
        self.pushButton_writepar = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_writepar.setFont(font)
        self.pushButton_writepar.setObjectName("pushButton_writepar")
        self.gridLayout.addWidget(self.pushButton_writepar, 6, 2, 1, 1)
        self.pushButton_readpar = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_readpar.setFont(font)
        self.pushButton_readpar.setObjectName("pushButton_readpar")
        self.gridLayout.addWidget(self.pushButton_readpar, 6, 5, 1, 1)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "Dialog"))
        self.label.setText(_translate("Config", "波特率"))
        self.comboBox_config_io.setItemText(0, _translate("Config", "开漏"))
        self.comboBox_config_io.setItemText(1, _translate("Config", "推挽"))
        self.comboBox_config_mode.setItemText(0, _translate("Config", "透传"))
        self.comboBox_config_mode.setItemText(1, _translate("Config", "定点"))
        self.label_3.setText(_translate("Config", "前向纠错"))
        self.label_4.setText(_translate("Config", "唤醒时间"))
        self.label_2.setText(_translate("Config", "空中速率"))
        self.label_5.setText(_translate("Config", "模块地址"))
        self.comboBox_config_parity.setItemText(0, _translate("Config", "8N1"))
        self.comboBox_config_parity.setItemText(1, _translate("Config", "8O1"))
        self.comboBox_config_parity.setItemText(2, _translate("Config", "8E1"))
        self.comboBox_config_baud.setItemText(0, _translate("Config", "1200"))
        self.comboBox_config_baud.setItemText(1, _translate("Config", "2400"))
        self.comboBox_config_baud.setItemText(2, _translate("Config", "4800"))
        self.comboBox_config_baud.setItemText(3, _translate("Config", "9600"))
        self.comboBox_config_baud.setItemText(4, _translate("Config", "19200"))
        self.comboBox_config_baud.setItemText(5, _translate("Config", "38400"))
        self.comboBox_config_baud.setItemText(6, _translate("Config", "57600"))
        self.comboBox_config_baud.setItemText(7, _translate("Config", "115200"))
        self.label_6.setText(_translate("Config", "校验位"))
        self.comboBox_config_speedinair.setItemText(0, _translate("Config", "0.3Kbps"))
        self.comboBox_config_speedinair.setItemText(1, _translate("Config", "1.2Kbps"))
        self.comboBox_config_speedinair.setItemText(2, _translate("Config", "2.4Kbps"))
        self.comboBox_config_speedinair.setItemText(3, _translate("Config", "4.8Kbps"))
        self.comboBox_config_speedinair.setItemText(4, _translate("Config", "9.6Kbps"))
        self.comboBox_config_speedinair.setItemText(5, _translate("Config", "19.2Kbps"))
        self.label_7.setText(_translate("Config", "发射功率"))
        self.label_8.setText(_translate("Config", "传输方式"))
        self.label_9.setText(_translate("Config", "IO驱动"))
        self.label_10.setText(_translate("Config", "模块信道"))
        self.comboBox_config_errcheck.setItemText(0, _translate("Config", "关闭"))
        self.comboBox_config_errcheck.setItemText(1, _translate("Config", "打开"))
        self.comboBox_config_wakeuptime.setItemText(0, _translate("Config", "250ms"))
        self.comboBox_config_wakeuptime.setItemText(1, _translate("Config", "500ms"))
        self.comboBox_config_wakeuptime.setItemText(2, _translate("Config", "750ms"))
        self.comboBox_config_wakeuptime.setItemText(3, _translate("Config", "1000ms"))
        self.comboBox_config_wakeuptime.setItemText(4, _translate("Config", "1250ms"))
        self.comboBox_config_wakeuptime.setItemText(5, _translate("Config", "1500ms"))
        self.comboBox_config_wakeuptime.setItemText(6, _translate("Config", "1750ms"))
        self.comboBox_config_wakeuptime.setItemText(7, _translate("Config", "2000ms"))
        self.comboBox_config_senddb.setItemText(0, _translate("Config", "20dBm"))
        self.comboBox_config_senddb.setItemText(1, _translate("Config", "17dBm"))
        self.comboBox_config_senddb.setItemText(2, _translate("Config", "14dBm"))
        self.comboBox_config_senddb.setItemText(3, _translate("Config", "10dBm"))
        self.pushButton_writepar.setText(_translate("Config", "写入参数"))
        self.pushButton_readpar.setText(_translate("Config", "读取参数"))

