# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_serialtool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SerialTool(object):
    def setupUi(self, SerialTool):
        SerialTool.setObjectName("SerialTool")
        SerialTool.resize(960, 746)
        self.gridLayoutWidget = QtWidgets.QWidget(SerialTool)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 172))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_serial_databits = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_serial_databits.setFont(font)
        self.label_serial_databits.setObjectName("label_serial_databits")
        self.gridLayout.addWidget(self.label_serial_databits, 2, 0, 1, 1)
        self.label_serial_port = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_serial_port.setEnabled(True)
        self.label_serial_port.setMaximumSize(QtCore.QSize(55, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_serial_port.setFont(font)
        self.label_serial_port.setObjectName("label_serial_port")
        self.gridLayout.addWidget(self.label_serial_port, 0, 0, 1, 1)
        self.label_serial_parity = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_serial_parity.setFont(font)
        self.label_serial_parity.setObjectName("label_serial_parity")
        self.gridLayout.addWidget(self.label_serial_parity, 3, 0, 1, 1)
        self.label_serial_baud = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_serial_baud.setFont(font)
        self.label_serial_baud.setObjectName("label_serial_baud")
        self.gridLayout.addWidget(self.label_serial_baud, 1, 0, 1, 1)
        self.label_serial_stopbits = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_serial_stopbits.setFont(font)
        self.label_serial_stopbits.setObjectName("label_serial_stopbits")
        self.gridLayout.addWidget(self.label_serial_stopbits, 4, 0, 1, 1)
        self.comboBox_serial_parity = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_serial_parity.setFont(font)
        self.comboBox_serial_parity.setObjectName("comboBox_serial_parity")
        self.comboBox_serial_parity.addItem("")
        self.comboBox_serial_parity.addItem("")
        self.comboBox_serial_parity.addItem("")
        self.gridLayout.addWidget(self.comboBox_serial_parity, 3, 1, 1, 1)
        self.comboBox_serial_databits = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_serial_databits.setFont(font)
        self.comboBox_serial_databits.setObjectName("comboBox_serial_databits")
        self.comboBox_serial_databits.addItem("")
        self.comboBox_serial_databits.addItem("")
        self.comboBox_serial_databits.addItem("")
        self.comboBox_serial_databits.addItem("")
        self.gridLayout.addWidget(self.comboBox_serial_databits, 2, 1, 1, 1)
        self.comboBox_serial_baud = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_serial_baud.setFont(font)
        self.comboBox_serial_baud.setObjectName("comboBox_serial_baud")
        self.comboBox_serial_baud.addItem("")
        self.comboBox_serial_baud.addItem("")
        self.comboBox_serial_baud.addItem("")
        self.comboBox_serial_baud.addItem("")
        self.comboBox_serial_baud.addItem("")
        self.comboBox_serial_baud.addItem("")
        self.gridLayout.addWidget(self.comboBox_serial_baud, 1, 1, 1, 1)
        self.comboBox_serial_stopbits = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_serial_stopbits.setFont(font)
        self.comboBox_serial_stopbits.setObjectName("comboBox_serial_stopbits")
        self.comboBox_serial_stopbits.addItem("")
        self.comboBox_serial_stopbits.addItem("")
        self.comboBox_serial_stopbits.addItem("")
        self.gridLayout.addWidget(self.comboBox_serial_stopbits, 4, 1, 1, 1)
        self.comboBox_serial_port = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_serial_port.setEnabled(True)
        self.comboBox_serial_port.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_serial_port.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_serial_port.setSizeIncrement(QtCore.QSize(0, 0))
        self.comboBox_serial_port.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_serial_port.setFont(font)
        self.comboBox_serial_port.setObjectName("comboBox_serial_port")
        self.gridLayout.addWidget(self.comboBox_serial_port, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(SerialTool)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 231, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_open = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout.addWidget(self.pushButton_open)
        self.pushButton_config = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_config.setFont(font)
        self.pushButton_config.setObjectName("pushButton_config")
        self.horizontalLayout.addWidget(self.pushButton_config)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(SerialTool)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 260, 231, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_dev_identify = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dev_identify.setFont(font)
        self.label_dev_identify.setObjectName("label_dev_identify")
        self.gridLayout_2.addWidget(self.label_dev_identify, 3, 0, 1, 1)
        self.lineEdit_dev_id = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_dev_id.setFont(font)
        self.lineEdit_dev_id.setObjectName("lineEdit_dev_id")
        self.gridLayout_2.addWidget(self.lineEdit_dev_id, 0, 2, 1, 1)
        self.lineEdit_dev_cmd = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_dev_cmd.setFont(font)
        self.lineEdit_dev_cmd.setObjectName("lineEdit_dev_cmd")
        self.gridLayout_2.addWidget(self.lineEdit_dev_cmd, 1, 2, 1, 1)
        self.label_dev_id = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dev_id.setFont(font)
        self.label_dev_id.setObjectName("label_dev_id")
        self.gridLayout_2.addWidget(self.label_dev_id, 0, 0, 1, 1)
        self.lineEdit_dev_identify = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_dev_identify.setFont(font)
        self.lineEdit_dev_identify.setObjectName("lineEdit_dev_identify")
        self.gridLayout_2.addWidget(self.lineEdit_dev_identify, 3, 2, 1, 1)
        self.lineEdit_dev_par = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_dev_par.setFont(font)
        self.lineEdit_dev_par.setObjectName("lineEdit_dev_par")
        self.gridLayout_2.addWidget(self.lineEdit_dev_par, 2, 2, 1, 1)
        self.label_dev_cmd = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dev_cmd.setFont(font)
        self.label_dev_cmd.setObjectName("label_dev_cmd")
        self.gridLayout_2.addWidget(self.label_dev_cmd, 1, 0, 1, 1)
        self.label_dev_par = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dev_par.setFont(font)
        self.label_dev_par.setObjectName("label_dev_par")
        self.gridLayout_2.addWidget(self.label_dev_par, 2, 0, 1, 1)
        self.pushButton_dev_send = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_dev_send.setFont(font)
        self.pushButton_dev_send.setObjectName("pushButton_dev_send")
        self.gridLayout_2.addWidget(self.pushButton_dev_send, 4, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(SerialTool)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(260, 10, 691, 561))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(SerialTool)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 580, 941, 156))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_hexselect = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_hexselect.setObjectName("checkBox_hexselect")
        self.gridLayout_3.addWidget(self.checkBox_hexselect, 4, 0, 1, 1)
        self.listWidget_hexshow = QtWidgets.QListWidget(self.gridLayoutWidget_3)
        self.listWidget_hexshow.setObjectName("listWidget_hexshow")
        self.gridLayout_3.addWidget(self.listWidget_hexshow, 3, 2, 1, 1)
        self.label_hex_display = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_hex_display.setFont(font)
        self.label_hex_display.setObjectName("label_hex_display")
        self.gridLayout_3.addWidget(self.label_hex_display, 3, 0, 1, 1)
        self.pushButton_test = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_test.setObjectName("pushButton_test")
        self.gridLayout_3.addWidget(self.pushButton_test, 4, 2, 1, 1)
        self.lcd_time = QtWidgets.QLCDNumber(SerialTool)
        self.lcd_time.setGeometry(QtCore.QRect(150, 540, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcd_time.setFont(font)
        self.lcd_time.setObjectName("lcd_time")
        self.label = QtWidgets.QLabel(SerialTool)
        self.label.setGeometry(QtCore.QRect(10, 480, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SerialTool)
        self.label_2.setGeometry(QtCore.QRect(130, 480, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_recvnum = QtWidgets.QLabel(SerialTool)
        self.label_recvnum.setGeometry(QtCore.QRect(60, 480, 54, 21))
        self.label_recvnum.setObjectName("label_recvnum")
        self.label_sendnum = QtWidgets.QLabel(SerialTool)
        self.label_sendnum.setGeometry(QtCore.QRect(180, 480, 61, 21))
        self.label_sendnum.setObjectName("label_sendnum")
        self.label_date = QtWidgets.QLabel(SerialTool)
        self.label_date.setGeometry(QtCore.QRect(10, 540, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.pushButton_clearcount = QtWidgets.QPushButton(SerialTool)
        self.pushButton_clearcount.setGeometry(QtCore.QRect(160, 510, 75, 23))
        self.pushButton_clearcount.setObjectName("pushButton_clearcount")

        self.retranslateUi(SerialTool)
        QtCore.QMetaObject.connectSlotsByName(SerialTool)

    def retranslateUi(self, SerialTool):
        _translate = QtCore.QCoreApplication.translate
        SerialTool.setWindowTitle(_translate("SerialTool", "Form"))
        self.label_serial_databits.setText(_translate("SerialTool", "数据位:"))
        self.label_serial_port.setText(_translate("SerialTool", "串口号:"))
        self.label_serial_parity.setText(_translate("SerialTool", "校验位:"))
        self.label_serial_baud.setText(_translate("SerialTool", "波特率:"))
        self.label_serial_stopbits.setText(_translate("SerialTool", "停止位:"))
        self.comboBox_serial_parity.setItemText(0, _translate("SerialTool", "NONE"))
        self.comboBox_serial_parity.setItemText(1, _translate("SerialTool", "ODD"))
        self.comboBox_serial_parity.setItemText(2, _translate("SerialTool", "EVEN"))
        self.comboBox_serial_databits.setItemText(0, _translate("SerialTool", "5"))
        self.comboBox_serial_databits.setItemText(1, _translate("SerialTool", "6"))
        self.comboBox_serial_databits.setItemText(2, _translate("SerialTool", "7"))
        self.comboBox_serial_databits.setItemText(3, _translate("SerialTool", "8"))
        self.comboBox_serial_baud.setItemText(0, _translate("SerialTool", "4800"))
        self.comboBox_serial_baud.setItemText(1, _translate("SerialTool", "9600"))
        self.comboBox_serial_baud.setItemText(2, _translate("SerialTool", "19200"))
        self.comboBox_serial_baud.setItemText(3, _translate("SerialTool", "38400"))
        self.comboBox_serial_baud.setItemText(4, _translate("SerialTool", "57600"))
        self.comboBox_serial_baud.setItemText(5, _translate("SerialTool", "115200"))
        self.comboBox_serial_stopbits.setItemText(0, _translate("SerialTool", "1"))
        self.comboBox_serial_stopbits.setItemText(1, _translate("SerialTool", "1.5"))
        self.comboBox_serial_stopbits.setItemText(2, _translate("SerialTool", "2"))
        self.pushButton_open.setText(_translate("SerialTool", "打开"))
        self.pushButton_config.setText(_translate("SerialTool", "配置Lora"))
        self.label_dev_identify.setText(_translate("SerialTool", "Identify:"))
        self.label_dev_id.setText(_translate("SerialTool", "设备ID:"))
        self.label_dev_cmd.setText(_translate("SerialTool", "命令CMD:"))
        self.label_dev_par.setText(_translate("SerialTool", "参数:"))
        self.pushButton_dev_send.setText(_translate("SerialTool", "发送"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SerialTool", "LastTime"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SerialTool", "ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SerialTool", "STATUS"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SerialTool", "CMD"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SerialTool", "BEEP"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SerialTool", "电量"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("SerialTool", "有车"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("SerialTool", "ULTRA"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("SerialTool", "心跳周期"))
        self.checkBox_hexselect.setText(_translate("SerialTool", "十六进制显示"))
        self.label_hex_display.setText(_translate("SerialTool", "HEX RECV:"))
        self.pushButton_test.setText(_translate("SerialTool", "test"))
        self.label.setText(_translate("SerialTool", "接收:"))
        self.label_2.setText(_translate("SerialTool", "发送:"))
        self.label_recvnum.setText(_translate("SerialTool", "TextLabel"))
        self.label_sendnum.setText(_translate("SerialTool", "TextLabel"))
        self.label_date.setText(_translate("SerialTool", "TextLabel"))
        self.pushButton_clearcount.setText(_translate("SerialTool", "清空计数"))

